EXAM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('questions/', include('questions.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),

    path('create/', views.create, name='create'),
    path('<int:pk>/delete', views.delete, name='delete'),

    path('complete/', views.complete, name='complete'),

    path('exam/', views.exam, name = 'exam'),

    path('grading/', views.grading, name = 'grading'),

    path('user/', views.user, name = 'user'),
]

questions/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.

class Test_User(models.Model):
    name = models.CharField(max_length = 100)
    e_mail = models.EmailField(max_length=254)

class Question(models.Model):
    # test_user = models.ForeignKey(Test_User, on_delete = models.CASCADE)
    num = models.IntegerField(validators=[MinValueValidator(1)])
    type = models.CharField(max_length=1, choices=[('M', '객관식'), ('S', '주관식')])
    title = models.CharField(max_length=300)

    #이미지
    image = models.ImageField(blank=True)

    # 객관식
    m1 = models.CharField(max_length=300, blank=True)
    m2 = models.CharField(max_length=300, blank=True)
    m3 = models.CharField(max_length=300, blank=True)
    m4 = models.CharField(max_length=300, blank=True)
  
    # 객관식 답
    answer_m = models.CharField(max_length=1, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], blank=True)

    # 주관식 답
    answer_s = models.CharField(max_length=200, blank=True)
    # 문제 생성 시간
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)



class User_Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 객관식 사용자 입력
    content_m = models.CharField(max_length=10, blank=True)
    # 주관식 사용자 입력
    content_s = models.CharField(max_length=300, blank=True)
    # 유저 정답 생성 시간
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

questions/forms.py
# questions/forms.py

from django import forms
from .models import Question, Test_User

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        labels = {
            'type' : '문제 유형',
            'num' : '문제 번호', 
            'title' : '문제 내용',
            'm1' : 'A.',
            'm2' : 'B.',
            'm3' : 'C.',
            'm4' : 'D.',
            'answer_m' : '정답',
            'answer_s' : '정답',
            'image' : '이미지 업로드',
        }

class UserForm(forms.ModelForm):
    class Meta:
        model = Test_User
        fields = '__all__'

# class AnswerForm(forms.ModelForm):
#     class Meta:
#         model = User_Answer
#         fields = ('question', 'content_m', 'content_s', )
#         labels  = {
#             'answer_m' : '정답',
#             'answer_s' : '정답',
#         }


# class QuestionForm_M(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = ('type', 'num', 'title', 'm1', 'm2', 'm3', 'm4', )
#         labels = {
#             'num' : '문제 번호', 
#             'title' : '문제 내용',
#             'm1' : 'A.',
#             'm2' : 'B.',
#             'm3' : 'C.',
#             'm4' : 'D.',
#         }

# class QuestionForm_S(forms.ModelForm):
#     class Meta:
#         model = Question
#         fields = ('type', 'num', 'title')
#         labels = {
#             'num' : '문제 번호', 
#             'title' : '문제 내용',
#         }

class M_choiceForm(forms.ModelForm):
    pass

questions/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import Question, User_Answer, Test_User
# from .forms import QuestionForm, AnswerForm
from .forms import QuestionForm, UserForm


def index(request):
    # 사용자가 이전에 응답을 제출했는지 확인합니다.
    # user_answer_exists = User_Answer.objects.exists()

    questions = Question.objects.order_by('num')

    context = {
        'questions' : questions,
        # 'user_answer_exists': user_answer_exists,
    }
    return render(request, 'questions/index.html', context)

# def index(request):
    
#     questions = Question.objects.order_by('num')
#     question_form = AnswerForm()

#     context = {
#         'question_form' : question_form,
#         'questions' : questions,
#     }
#     return render(request, 'questions/index.html', context)

def detail(request, pk):
    question = Question.objects.get(pk = pk)

    context = {
        'question' : question,
    }

    return render(request, 'questions/detail.html', context)


# CRUD 구현
def create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        # print(form)
        if form.is_valid():
            question = form.save()
            return redirect('questions:detail', question.pk)
    else:
        form = QuestionForm()

    context = {
        'form' : form,
        # 'userform' : userform,
    }
    return render(request, 'questions/create.html', context)


def delete(request, pk):
    question = Question.objects.get(pk = pk)
    question.delete()
    return redirect('questions:index')

def complete(request):
    if request.method == 'POST':
        # 사용자가 선택한 질문의 ID를 폼으로부터 받아옴
        # selected_question_id = request.POST.get('question_id')
        # 선택한 질문 객체 가져오기
        # selected_question = Question.objects.get(pk=selected_question_id)
        # 답변 폼 생성 및 유효성 검사
        # answer_form = AnswerForm(request.POST)

        user_answers = []

        for key, value in request.POST.items():
            if key.endswith('-select'):
                question_pk, question_type = key.split('-')[:-1]
                answer = {
                    'question_id': int(question_pk),
                    'content_m': value if question_type == 'M' else '',
                    'content_s': value if question_type == 'S' else '',
                }
                user_answers.append(answer)

        # user_answers에 있는 데이터를 User_Answer 모델에 저장
        for answer_data in user_answers:
            question = Question.objects.get(pk=answer_data['question_id'])
            # 해당 사용자의 이전 답변 삭제
            
            user_answer = User_Answer.objects.create(
                question=question,
                content_m=answer_data['content_m'],
                content_s=answer_data['content_s']
            )

        return redirect('questions:complete')
    else:
        return render(request, 'questions/complete.html')
        


        # if answer_form.is_valid():
            
            # DB에 저장되기 전에 답변 인스턴스를 가져오고 선택한 질문과 연결
            # answer = answer_form.save(commit=False)
            # answer.question = selected_question  # 선택한 질문과 연결
            # answer.save()  # 답변 저장
            # return redirect('questions:complete')
    # else:
    #     # GET 요청 시, 모든 질문을 가져와서 보여줌
    #     questions = Question.objects.all()
    #     answer_form = AnswerForm()
    #     context = {
    #         'questions': questions,
    #         'answer_form': answer_form,
    #     }
    # return render(request, 'questions/index.html', context)


    # if request.method == 'POST':
    #     form2 = AnswerForm(request.POST)
    #     print(form2)
    #     if form2.is_valid():
    #         answer = form2.save()
    #         return redirect('questions:complete', answer)
    # else:
    #     form2 = AnswerForm()

    # context = {
    #     'form2' : form2,
    # }


def exam(request):
    questions = Question.objects.order_by('num')

    context = {
        'questions' : questions,
    }
    return render(request, 'questions/exam.html', context)


def grading(request):
    questions = Question.objects.order_by('num')
    user_answers = User_Answer.objects.order_by('question_id')
    result = []
    total = 0
    for question, user_answer in zip(questions, user_answers):
        if question.type == 'M':
            answer = question.answer_m
        else:
            answer = question.answer_s
        if question.type == 'M':
            content = user_answer.content_m
        else:
            content = user_answer.content_s
        if answer == content:
            grade = 5
        else:
            grade = 0
        total += grade
        result.append({
            'name' : '',
            'e_mail' :  '',
            'created_at' : user_answer.created_at,
            'updated_at' : user_answer.updated_at,
            'num' : question.num,
            'content' : content,
            'answer': answer,
            'grade' : grade,
        })

    context = {
        'result' : result,
        'total' : total,
    }
    print(result)
    return render(request, 'questions/grading.html', context)

def user(request):
    if request.method == 'POST':
        # global userform
        userform = UserForm(request.POST)
    # print(form)
        if userform.is_valid():
            question = userform.save()
            return redirect('questions:exam')
    else:
        userform = UserForm()

    context = {
        'userform' : userform,
    }
    return render(request, 'questions/user.html', context)

questions/templates/questions/complete.html
{% extends "base.html" %}

{% block content %}

<h1>수고하셨습니다.</h1>

{% endblock content %}

questions/templates/questions/create.html
{% extends "base.html" %}

{% block content %}
    <h1>문제 출제 페이지</h1>


    <form action="{% url 'questions:create' %}" method="POST" id="questionTypeForm">
      {% csrf_token %}
      {% comment %} {{ form.as_p }} {% endcomment %}
      {{ form.type }}
      <button type="button" onclick="showForm()">유형 선택</button>
    </form>

    <form id="formM" action="{% url 'questions:create' %}" enctype="multipart/form-data" method="POST" style="display:none;">
        {% csrf_token %}
        <select name="type" required id="id_type" style="display:none">
          <option value="">---------</option>       
          <option value="M" selected>객관식</option>     
          <option value="S">주관식</option>  
        </select>
        <br>
        {{ form.num.label_tag }}
        {{ form.num}}
        <br>
        {{ form.title.label_tag }}
        {{ form.title }}
        <br>
        {{ form.m1.label_tag }}
        {{ form.m1 }}
        <br>
        {{ form.m2.label_tag }}
        {{ form.m2 }}
        <br>
        {{ form.m3.label_tag }}
        {{ form.m3 }}
        <br>
        {{ form.m4.label_tag }}
        {{ form.m4 }}
        <br>
        {{form.image.label_tag}}
        {{form.image}}
        <hr>
        {{form.answer_m.label_tag}}
        {{form.answer_m}}
        <input type="submit" value="Submit">
    </form>

    <form id="formS" action="{% url 'questions:create' %}" enctype="multipart/form-data" method="POST" style="display:none;">
        {% csrf_token %}
        {% comment %} {{ form_s.as_p }} {% endcomment %}
        <select name="type" required id="id_type" style="display:none">
          <option value="">---------</option>       
          <option value="M">객관식</option>     
          <option value="S" selected>주관식</option>  
        </select>
        <br>
        {{ form.num.label_tag }}
        {{ form.num}}
        <br>
        {{ form.title.label_tag }}
        {{ form.title }}
        <br>
        {{form.image.label_tag}}
        {{form.image}}
        <br>
        {{ form.answer_s.label_tag }}
        {{ form.answer_s }}
        <br>
        <input type="submit" value="Submit">
    </form> 


    <hr>


    <a href="{% url 'questions:index' %}">[back]</a>
{% endblock content %}

    {% comment %} 객관식, 주관식 선택 토글버튼 {% endcomment %}
    {% comment %} <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          문제 유형
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#" onclick="setType('M')">객관식</a></li>
          <li><a class="dropdown-item" href="#" onclick="setType('S')">주관식</a></li>
        </ul>
    </div>


    <form id="questionFormM" action="{% url 'questions:create' %}" method="POST" style="display:none;">
      {% csrf_token %}
      {{ form_m.as_p }}
      <input type="submit">
    </form>
  
    <form id="questionFormS" action="{% url 'questions:create' %}" method="POST" style="display:none;">
      {% csrf_token %}
      {{ form_s.as_p }}
      <input type="submit">
    </form> {% endcomment %}

questions/templates/questions/detail.html
{% extends "base.html" %}


{% block content %}

    <h2 id = 'questionFormM'>문제 번호 : {{question.num}}</h2>

    <P id = 'questionFormM'>문제 내용 : {{question.title}}</P>
    {% if question.image %}
        <img src="{{ question.image.url }}" alt="img">
    {% endif %}
    {% if question.type == 'M' %}
        <p id = 'questionFormM'> A. {{question.m1}}</p>
        <p id = 'questionFormM'> B. {{question.m2}}</p>
        <p id = 'questionFormM'> C. {{question.m3}}</p>
        <p id = 'questionFormM'> D. {{question.m4}}</p>
        <p id = 'questionFormM'> 정답 : {{question.answer_m}}</p>
    {% else %}
        <P id = 'questionFormM'>정답 : {{question.answer_s}}</P>
    {% endif %}

    
    <hr>



    <form action="{% url 'questions:delete' question.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>


    <hr>
    <a href="{% url 'questions:index' %}">[back]</a>
{% endblock content %}

questions/templates/questions/exam.html
{% extends "base.html" %}

{% block content %}

<h1> 오늘의 시험 </h1>

<hr>
<form action="{% url 'questions:complete'%}" method="POST" >
    {% for question in questions %}
        <p>문제 번호 : {{question.num}}</p>
        <p>문제 형식 : {% if question.m1 %}객관식{% else %}주관식{% endif %}</p>
        <p>문제 내용 : {{question.title}} </p>
        {% if question.type == 'M' %}
            <p id = 'questionFormM'> A. {{question.m1}}</p>
            <p id = 'questionFormM'> B. {{question.m2}}</p>
            <p id = 'questionFormM'> C. {{question.m3}}</p>
            <p id = 'questionFormM'> D. {{question.m4}}</p> 
            
            {% csrf_token %}
            
            답 : <select name="{{ question.pk }}-{{ question.type }}-select" id="{{ question.pk }}-{{ question.type }}-select">
                <option value="---------">---------</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
            </select>

            {% comment %} {{ question_form.content_m }} {% endcomment %}
        {% else %}

            {% csrf_token %}

            답 : <input type="text" id="{{ question.pk }}-{{ question.type }}-select" name="{{ question.pk }}-{{ question.type }}-select">

            {% comment %} {{ question_form.content_s }} {% endcomment %}
            
        {% endif %}
        <hr>
    {% endfor %}
    <input type="submit" id = "submit-btn" value="제출하기">
</form>


{% endblock content %}

questions/templates/questions/grading.html
{% extends "base.html" %}


{% block content %}
<h1>채점 페이지</h1>

{% for item in result %}
    {% if forloop.first %}
        <p>Name: {{ item.name }}</p>
        <p>E-mail: {{ item.e_mail }}</p>
        <p>첫 제출: {{ item.created_at }}</p>
        <p>마지막 제출: {{ item.updated_at }}</p>
        <p>총 점수: {{total}}</p>
    {% endif %}

    <p>{{item.num}} 번: {{ item.content }}</p>
    <p>{{item.num}} 번 정답: {{item.answer }}</p>
    <p>{{item.num}} 번 점수: {{item.grade }}</p>
{% endfor %}

<hr>
<a href="{% url 'questions:index' %}">[back]</a>
{% endblock content %}

questions/templates/questions/index.html
{% extends "base.html" %}


{% block content %}
<h1><홈> 문제 출제 페이지</h1>

<hr>

<a href="{% url 'questions:create' %}">문제 출제</a>

<hr>

<a href="{% url "questions:user" %}">시험 보기</a>

<hr>

<a href="{% url "questions:grading" %}">채점 하기</a>

<hr>
<form action="{% url 'questions:complete'%}" method="POST" >
    {% for question in questions %}
        <a href="{% url "questions:detail" question.pk %}">
            <p>문제 번호 : {{question.num}}</p>
        </a>
        <p>문제 형식 : {% if question.m1 %}객관식{% else %}주관식{% endif %}</p>

        {% if question.image %}
            <img src="{{ question.image.url }}" alt="img">
        {% endif %}

        <p>문제 내용 : {{question.title}} </p>

        {% if question.type == 'M' %}
            <p id = 'questionFormM'> A. {{question.m1}}</p>
            <p id = 'questionFormM'> B. {{question.m2}}</p>
            <p id = 'questionFormM'> C. {{question.m3}}</p>
            <p id = 'questionFormM'> D. {{question.m4}}</p> 
            
            {% csrf_token %}

            정답 : <select name="{{ question.pk }}-{{ question.type }}-select" id="{{ question.pk }}-{{ question.type }}-select">
                <option value="---------">---------</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
            </select>

            {% comment %} {{ question_form.content_m }} {% endcomment %}
        {% else %}

            {% csrf_token %}

            정답 : <input type="text" id="{{ question.pk }}-{{ question.type }}-select" name="{{ question.pk }}-{{ question.type }}-select">

            {% comment %} {{ question_form.content_s }} {% endcomment %}
            
        {% endif %}
        <hr>
    {% endfor %}
    <input type="submit" id = "submit-btn" value="제출 TEST">

</form>
{% endblock content %}

questions/templates/questions/user.html
{% extends "base.html" %}

{% block content %}
<h1>안녕하세요 시험 시작하겠습니다.</h1>


<form action="{% url 'questions:user'%}" method="POST" >
    {% csrf_token %}
    {{userform.as_p}}
    <input type="submit" value="시험 시작">   
</form> 

{% endblock content %}